name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-15
    strategy:
      matrix:
        device: [iPhone 16 Pro]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Listar SDKs do iOS disponíveis
        run: |
          xcodebuild -showsdks

      - name: Build and test
        run: |
          xcodebuild -scheme "IMC" -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2" test
